// GENERATED by scripts/write-release.mjs. Do not edit.
//
// null outside CI, which is why the committed copy says null: a local build
// then rewrites it identically and leaves the working tree clean.
export const RELEASE: string | null = null;
