/**
 * Writes the deployed commit into a source file, so Sentry can tag an error
 * with the deploy it came from.
 *
 * Why the commit SHA and not the semantic-release version, which the phase plan
 * asks for: the production bundle is built by Vercel, and Vercel builds from a
 * branch push. semantic-release runs afterwards, in GitHub Actions, and tags a
 * commit that has already been built and deployed. At the moment this file is
 * written the version does not exist yet, and `package.json` stays at 0.0.0
 * because semantic-release writes nothing back to the repository. The SHA is
 * the one identifier that is both available here and unambiguous later.
 *
 * It must also match whatever source maps are uploaded against, or a stack
 * trace resolves against the wrong build.
 *
 * With no CI environment the file is written with `null`, which is exactly what
 * is committed -- so a local build leaves the working tree clean rather than
 * showing a spurious change on every run.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { releaseId } from './release-id.mjs';

const OUTPUT = new URL('../src/app/core/monitoring/release.ts', import.meta.url);

const sha = releaseId();
const literal = sha === null ? 'null' : `'${sha}'`;

const contents = `// GENERATED by scripts/write-release.mjs. Do not edit.
//
// null outside CI, which is why the committed copy says null: a local build
// then rewrites it identically and leaves the working tree clean.
export const RELEASE: string | null = ${literal};
`;

const existing = (() => {
  try {
    return readFileSync(OUTPUT, 'utf8');
  } catch {
    return null;
  }
})();

if (existing === contents) {
  console.log(`Release unchanged: ${sha ?? '(none, local build)'}`);
} else {
  writeFileSync(OUTPUT, contents);
  console.log(`Release written: ${sha ?? '(none, local build)'}`);
}
